ALTER TABLE public.instance_health
  ADD COLUMN IF NOT EXISTS reconnect_attempts INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS next_reconnect_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS last_reconnect_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS last_reconnect_error TEXT,
  ADD COLUMN IF NOT EXISTS reconnect_given_up BOOLEAN NOT NULL DEFAULT false;